name: Campus Canteen CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: Backend
        run: npm install

      - name: Test Backend
        working-directory: Backend
        run: node --check server.js

      - name: Build Docker Image
        working-directory: Backend
        run: docker build -t campus-canteen-backend .

      - name: Deploy to EC2 #1
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_1 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/campus-canteen-queue-app
            git pull origin main
            cd Backend
            sudo docker build -t campus-canteen-backend .
            sudo docker ps -q --filter "publish=3000" | xargs -r sudo docker stop
            sudo docker ps -aq --filter "publish=3000" | xargs -r sudo docker rm
            sudo docker rm -f campus-canteen-backend || true
            sudo docker run -d \
              --name campus-canteen-backend \
              --restart unless-stopped \
              --env-file .env \
              -p 3000:3000 \
              campus-canteen-backend

      - name: Deploy to EC2 #2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST_2 }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/campus-canteen-queue-app
            git pull origin main
            cd Backend
            sudo docker build -t campus-canteen-backend .
            sudo docker ps -q --filter "publish=3000" | xargs -r sudo docker stop
            sudo docker ps -aq --filter "publish=3000" | xargs -r sudo docker rm
            sudo docker rm -f campus-canteen-backend || true
            sudo docker run -d \
              --name campus-canteen-backend \
              --restart unless-stopped \
              --env-file .env \
              -p 3000:3000 \
              campus-canteen-backend