name: Campus Canteen CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: Backend
        run: npm install

      - name: Test Backend
        working-directory: Backend
        run: node --check server.js

      - name: Build Docker Image
        working-directory: Backend
        run: docker build -t campus-canteen-backend .

      - name: Deployment Complete
        run: echo "Build and test completed successfully!"